redmine_db_host: "rc1a-himn4l9jchjkkgt1.mdb.yandexcloud.net,rc1b-hp0ub6ppegamcut1.mdb.yandexcloud.net"
redmine_db_port: 6432
redmine_db_name: "app_db"
redmine_db_user: "app_user"
redmine_db_password: "{{ vault_redmine_db_password }}"
redmine_db_sslmode: "require"

datadog_api_key: "{{ vault_datadog_api_key }}"
datadog_site: "datadoghq.eu"
datadog_checks:
  http_check:
    init_config:
    instances:
      - name: redmine
        url: "http://localhost:{{ redmine_port }}"
        timeout: 5
